<center>Name:Quratulain<br>
Gmail:QuratulainkhanAIML1@outlook.com<br>
Github:QuratulainkhanAIML1<br>
Topic:Assignment1</center>

Install libraries

In [1]:
%pip install pandas


Note: you may need to restart the kernel to use updated packages.


In [2]:
%pip install numpy


Note: you may need to restart the kernel to use updated packages.


Import libraries

In [3]:
import pandas as pd
import numpy as np

Create a pandas Series with the values [1, 3, 5, np.nan, 6, 8].

In [4]:
data = pd.Series([1, 3, 5, np.nan, 6, 8])
print(data)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


Generate a date range starting from "2024-01-01" with a period of 6 days.

In [5]:
dates = pd.date_range(start="2024-01-01", periods=6)
print(dates)

DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05', '2024-01-06'],
              dtype='datetime64[ns]', freq='D')


Create a pandas DataFrame with 6 rows and 4 columns of random numbers, indexed by the date range generated in question 5, and columns named A, B, C, D.

In [6]:
dates = pd.date_range(start="2024-01-01", periods=6)

# Create DataFrame with random numbers
dates= pd.DataFrame(np.random.randn(6, 4), index=dates, columns=['A', 'B', 'C', 'D'])
dates

A         B         C         D
2024-01-01 -0.683502 -0.277457 -0.878199  0.396348
2024-01-02 -1.137083  0.954583 -0.175268 -1.240513
2024-01-03 -1.351875  1.141696  0.053363 -0.433388
2024-01-04  0.083324 -0.803758 -0.451653  0.530138
2024-01-05 -0.303110  0.493536  1.630690 -0.880421
2024-01-06  0.331985  0.820709  0.754733 -1.428603

Create a pandas DataFrame with the following data:
A: 1.0
B: Timestamp "2013-01-02"
C: Series of 1 with index from 0 to 3, dtype "float32"
D: Array of [3, 3, 3, 3], dtype "int32"
E: Categorical ["test", "train", "test", "train"]

In [7]:
df = pd.DataFrame({
    'A': 1.0,
    'B': pd.Timestamp('2013-01-02'),
    'C': pd.Series(1, index=list(range(4)), dtype='float32'),
    'D': np.array([3] * 4, dtype='int32'),
    'E': pd.Categorical(["test", "train", "test", "train"]),
    'F': 'foo'
})

print(df)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo


Display datatypes

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype        
---  ------  --------------  -----        
 0   A       4 non-null      float64      
 1   B       4 non-null      datetime64[s]
 2   C       4 non-null      float32      
 3   D       4 non-null      int32        
 4   E       4 non-null      category     
 5   F       4 non-null      object       
dtypes: category(1), datetime64[s](1), float32(1), float64(1), int32(1), object(1)
memory usage: 288.0+ bytes


View the First Few Rows.

In [9]:
df.head()

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

Show the first 5 rows of the DataFrame created in question 6.

In [10]:
dates.head(5)

A         B         C         D
2024-01-01 -0.683502 -0.277457 -0.878199  0.396348
2024-01-02 -1.137083  0.954583 -0.175268 -1.240513
2024-01-03 -1.351875  1.141696  0.053363 -0.433388
2024-01-04  0.083324 -0.803758 -0.451653  0.530138
2024-01-05 -0.303110  0.493536  1.630690 -0.880421

View the Last Few Rows.

In [11]:
df.tail()

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

Show the last 3 rows of the DataFrame created in question 6.

In [12]:
dates.tail(3)

A         B         C         D
2024-01-04  0.083324 -0.803758 -0.451653  0.530138
2024-01-05 -0.303110  0.493536  1.630690 -0.880421
2024-01-06  0.331985  0.820709  0.754733 -1.428603

Display the index of the DataFrame created in question 7.

In [13]:
print(df.index)

Index([0, 1, 2, 3], dtype='int64')


Display the column names of the DataFrame created in question 6.

In [14]:
print(dates.columns)

Index(['A', 'B', 'C', 'D'], dtype='object')


Convert the DataFrame created in question 6 to a numpy array.

In [15]:
array = dates.to_numpy()
print(array)

[[-0.68350237 -0.27745664 -0.878199    0.39634794]
 [-1.13708266  0.9545829  -0.17526769 -1.24051349]
 [-1.35187518  1.14169633  0.05336318 -0.43338838]
 [ 0.08332447 -0.80375798 -0.45165255  0.53013752]
 [-0.30310998  0.49353567  1.63068965 -0.88042149]
 [ 0.33198462  0.82070917  0.75473299 -1.42860319]]


Convert the DataFrame created in question 6 to a numpy array.

In [16]:
array = df.to_numpy()
print(array)

[[1.0 Timestamp('2013-01-02 00:00:00') 1.0 3 'test' 'foo']
 [1.0 Timestamp('2013-01-02 00:00:00') 1.0 3 'train' 'foo']
 [1.0 Timestamp('2013-01-02 00:00:00') 1.0 3 'test' 'foo']
 [1.0 Timestamp('2013-01-02 00:00:00') 1.0 3 'train' 'foo']]


Provide a summary description of the DataFrame created in question 6.

In [17]:
dates.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.510044  0.388218  0.155611 -0.509407
std    0.668710  0.768189  0.904685  0.827516
min   -1.351875 -0.803758 -0.878199 -1.428603
25%   -1.023688 -0.084709 -0.382556 -1.150490
50%   -0.493306  0.657122 -0.060952 -0.656905
75%   -0.013284  0.921114  0.579391  0.188914
max    0.331985  1.141696  1.630690  0.530138

Transpose the DataFrame created in question 6.

In [18]:
dates.T

2024-01-01  2024-01-02  2024-01-03  2024-01-04  2024-01-05  2024-01-06
A   -0.683502   -1.137083   -1.351875    0.083324   -0.303110    0.331985
B   -0.277457    0.954583    1.141696   -0.803758    0.493536    0.820709
C   -0.878199   -0.175268    0.053363   -0.451653    1.630690    0.754733
D    0.396348   -1.240513   -0.433388    0.530138   -0.880421   -1.428603

Sort the DataFrame created in question 6 by the index (axis=1) in descending order.

In [19]:
dates_sorted = dates.sort_index(axis=1, ascending=False)
print(dates_sorted)

                   D         C         B         A
2024-01-01  0.396348 -0.878199 -0.277457 -0.683502
2024-01-02 -1.240513 -0.175268  0.954583 -1.137083
2024-01-03 -0.433388  0.053363  1.141696 -1.351875
2024-01-04  0.530138 -0.451653 -0.803758  0.083324
2024-01-05 -0.880421  1.630690  0.493536 -0.303110
2024-01-06 -1.428603  0.754733  0.820709  0.331985


Sort the DataFrame created in question 6 by the values in column B.

In [20]:
dates_sorted_by_B = dates.sort_values(by='B')
print(dates_sorted_by_B)

                   A         B         C         D
2024-01-04  0.083324 -0.803758 -0.451653  0.530138
2024-01-01 -0.683502 -0.277457 -0.878199  0.396348
2024-01-05 -0.303110  0.493536  1.630690 -0.880421
2024-01-06  0.331985  0.820709  0.754733 -1.428603
2024-01-02 -1.137083  0.954583 -0.175268 -1.240513
2024-01-03 -1.351875  1.141696  0.053363 -0.433388


Select the column A from the DataFrame created in question 6.

In [21]:
dates["A"]

2024-01-01   -0.683502
2024-01-02   -1.137083
2024-01-03   -1.351875
2024-01-04    0.083324
2024-01-05   -0.303110
2024-01-06    0.331985
Freq: D, Name: A, dtype: float64

Select the first 3 rows of the DataFrame created in question 6.

In [22]:
sd =df.loc[1:3]
sd

A          B    C  D      E    F
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

Select the rows from "2024-01-02" to "2024-01-04" from the DataFrame created in question 6.

In [23]:
sc=dates.loc[['2024-01-02', '2024-01-03', '2024-01-04']]
sc

A         B         C         D
2024-01-02 -1.137083  0.954583 -0.175268 -1.240513
2024-01-03 -1.351875  1.141696  0.053363 -0.433388
2024-01-04  0.083324 -0.803758 -0.451653  0.530138