<center>Name:Quratulain<br>
Gmail:QuratulainkhanAIML1@outlook.com<br>
Github:QuratulainkhanAIML1<br>
Topic:Assignment1</center>

In [1]:
import pandas as pd
import numpy as np

### Sales Data Analysis

In [2]:
Daily_sales =np.array([105, 150, 200, 125, 200, 250, 180, 110, 160, 230, 210, 190, 140, 180, 200, 120, 170, 334, 190, 100, 150, 210, 180, 130, 50, 200, 110, 160, 230])
Daily_sales

array([105, 150, 200, 125, 200, 250, 180, 110, 160, 230, 210, 190, 140,
       180, 200, 120, 170, 334, 190, 100, 150, 210, 180, 130,  50, 200,
       110, 160, 230])

In [3]:
Total_sales=Daily_sales.sum()
Total_sales

np.int64(4964)

In [4]:
Average_sales=Daily_sales.mean()
Average_sales

np.float64(171.17241379310346)

In [5]:
Highest_Day_sales=Daily_sales.argmax()+1
Highest_Day_sales

np.int64(18)

In [6]:
HeighestSale_Amount= Daily_sales.max()
HeighestSale_Amount

np.int64(334)

### Weather Data Processing

In [7]:
Weekly_Temperatures = np.array([[31,43,33,37,32,36,30],
                                [39,42,34,31,36,32,38],
                                [33,41,30,32,35,38,36],
                               ])
Weekly_Temperatures 

array([[31, 43, 33, 37, 32, 36, 30],
       [39, 42, 34, 31, 36, 32, 38],
       [33, 41, 30, 32, 35, 38, 36]])

In [8]:
Veg_temp_Day=Weekly_Temperatures.mean(axis=0)
Veg_temp_Day

array([34.33333333, 42.        , 32.33333333, 33.33333333, 34.33333333,
       35.33333333, 34.66666667])

In [9]:
for day in range(7):
    print(f"Day {day+1}: {Veg_temp_Day[day]:.2f} degrees Celsius")

Day 1: 34.33 degrees Celsius
Day 2: 42.00 degrees Celsius
Day 3: 32.33 degrees Celsius
Day 4: 33.33 degrees Celsius
Day 5: 34.33 degrees Celsius
Day 6: 35.33 degrees Celsius
Day 7: 34.67 degrees Celsius


### Financial Analysis

In [10]:
Prices = np.array([109, 115, 104, 135, 136, 137, 138, 140, 142, 144, 145, 147, 148,149, 150, 151])
Prices

array([109, 115, 104, 135, 136, 137, 138, 140, 142, 144, 145, 147, 148,
       149, 150, 151])

In [11]:
Monthly_return = (Prices[-1]-Prices[0])/Prices[0]*100
Monthly_return 

np.float64(38.53211009174312)

### Student Grades Analysis

In [12]:
Grades_std = np.array([[70, 95, 88],[75, 60, 80],[80, 89, 92],[81, 77, 65]])
Grades_std

array([[70, 95, 88],
       [75, 60, 80],
       [80, 89, 92],
       [81, 77, 65]])

In [13]:
Avg_grade_pr_std = np.mean(Grades_std, axis=1)
Avg_grade_pr_std

array([84.33333333, 71.66666667, 87.        , 74.33333333])

In [14]:
Class_avg_per_subj = np.mean(Grades_std, axis=0)
Class_avg_per_subj

array([76.5 , 80.25, 81.25])

### Image Processing

In [15]:
img = np.array([[0, 130, 255],[50, 167, 138],[255, 190, 0]])
img

array([[  0, 130, 255],
       [ 50, 167, 138],
       [255, 190,   0]])

In [16]:
#Img range 0 to 1
normalized_img = img / 255.0
normalized_img

array([[0.        , 0.50980392, 1.        ],
       [0.19607843, 0.65490196, 0.54117647],
       [1.        , 0.74509804, 0.        ]])

### Population Growth Analysis

In [17]:
Population_Data = np.array([1700, 1650, 1800, 2300, 1200, 1050, 1300, 1100, 1600, 1500])

Population_Data

array([1700, 1650, 1800, 2300, 1200, 1050, 1300, 1100, 1600, 1500])

In [18]:
annual_growth_rate = np.diff(Population_Data) / Population_Data[:-1] * 100
highest_growth_year = np.argmax(annual_growth_rate) + 1  

In [19]:
annual_growth_rate


array([ -2.94117647,   9.09090909,  27.77777778, -47.82608696,
       -12.5       ,  23.80952381, -15.38461538,  45.45454545,
        -6.25      ])

In [20]:
highest_growth_year

np.int64(8)

Traffic Data Analysis

In [21]:
#Data: 7 days, 24 hrs
Trafic = np.random.randint(20, 170, size=(7, 24))
Trafic 

array([[ 97,  52, 112, 103,  33,  49,  47,  21,  71, 131,  66,  41,  33,
        147, 162, 139,  68,  81, 164, 154, 135,  53,  74,  84],
       [151,  30,  22, 168,  70, 162,  46,  22, 144, 146,  86, 129,  96,
        153,  57,  80, 143,  88, 155,  45,  88,  80,  71, 130],
       [ 58,  74,  40, 146,  77, 113,  46, 128,  31,  40,  63,  40, 169,
         34,  25,  59, 121,  44, 162,  66,  92,  51, 121, 149],
       [121,  57, 106, 105, 123,  99,  41, 132, 111,  61, 134,  61,  32,
         22, 164,  94, 121,  80, 135,  58, 113, 110,  76,  37],
       [106, 156, 146, 100,  57, 119, 103, 159, 147, 111,  97, 146,  49,
        156, 130,  33,  75,  28, 107,  50,  68, 131,  32, 116],
       [100,  82, 108, 165, 151,  44, 108, 137,  57,  81, 163,  58, 150,
        150, 109,  90, 152,  95,  95, 109,  42, 164,  44,  89],
       [ 58, 100,  46,  44,  20,  40, 147, 119, 148,  70, 144,  31,  83,
         91,  92,  98,  48,  20, 166, 133,  48,  91,  63,  74]],
      dtype=int32)

In [22]:
total_trafic_per_day = np.sum(Trafic, axis=1)
Busy_hour_in_wk = np.argmax(np.sum(Trafic, axis=0))

In [23]:
total_trafic_per_day 

array([2117, 2362, 1949, 2193, 2422, 2543, 1974])

In [24]:
Busy_hour_in_wk

np.int64(18)

Product Inventory Management:

In [25]:
Stock_levels = np.array([55, 65, 75, 35, 50, 25])


In [26]:
#threshold 50 units
reorder_list = np.where(Stock_levels < 50)[0]

reorder_list

array([3, 5])


Game Score Analysis

In [27]:
#Data of 5 players and 10 rounds
Score = np.random.randint(80, 320, size=(5, 20))

In [28]:
# Player with highest ave score
highest_avg_scoreplayer = np.argmax(np.mean(Score, axis=1))

# Round with highest T score
highest_total_scorer_ound = np.argmax(np.sum(Score, axis=0))

In [29]:
highest_avg_scoreplayer

np.int64(3)

In [30]:
highest_total_scorer_ound

np.int64(0)

Financial Portfolio Analysis

In [31]:
# 4 assets, 30 days)
Return = np.random.randn(6, 40)

Overall_daily_return = np.mean(Return, axis=0)

# Asset with highest volatility
Highest_volatility_asset = np.argmax(np.std(Return, axis=1))

Overall_daily_return

array([-0.23049504, -0.42929206,  0.12982691,  0.12137713,  0.35113956,
        0.49412324, -0.15558154,  0.15852761,  0.04809244, -0.56184233,
        0.18962923,  0.34576619,  0.38915551,  0.44408519,  0.55192905,
       -0.78961017, -0.56702584,  0.23121037, -0.9245974 , -0.06670674,
       -0.6781276 ,  0.87928945,  0.60400073,  0.41489001,  0.04159948,
       -0.61782122, -0.73716702, -0.26285548, -0.2825537 , -0.20343912,
       -0.10542573, -0.55299865,  0.21543539, -0.19889043, -0.39128336,
       -0.10515305, -0.87097362, -0.03746441,  0.29700065, -0.14458336])

In [32]:
Highest_volatility_asset

np.int64(3)