<center>Name:Quratulain<br>
Email:QuratulainkhanAIML1@hotmail.com<br>
Github:QuratulainkhanAIML1<br>
Title: NumpyPracticebyq</center>

Install Required Libraries

In [3]:
%pip install pandas
%pip install numpy

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


import libraries

In [4]:
import pandas as pd
import numpy as np

Load the Data:

In [5]:
df=pd.read_csv('data.csv')

In [6]:
df

Name Designation Gender    Age     Salary
0         Mukhtar   Professor      M   37.0   115000.0
1           Azziz     Teacher      M   30.0    35000.0
2          Mohsin    Engineer      M   29.0    50000.0
3   Naveed Fatima     Analyst      F   30.0    70000.0
4           Babar    Engineer      F   25.0  1500000.0
5            Aqsa   Scientist      F   22.0        NaN
6           Rafia     Analyst      F   29.0    20000.0
7           Samra   Scientist      F   26.0   115000.0
8            Eman    Engineer      F   28.0    35000.0
9        Abdullah     Teacher      M   55.0        NaN
10          Mosib   professor      M   60.0    70000.0
11          Ahmed    engineer      M    NaN    90000.0
12          Ahsan     trainer      M  156.0   110000.0
13          Wajid     teacher      M   67.0     2000.0
14          Naeem     trainer      M   80.0    16000.0
15         Qaisar   professor      M   20.0   170000.0
16          Wajid    Engineer      M   85.0   190000.0

 Convert the DataFrame to a NumPy array

In [7]:
data_array = df.to_numpy()
print(data_array)

[['Mukhtar' 'Professor' 'M' 37.0 115000.0]
 ['Azziz' 'Teacher' 'M' 30.0 35000.0]
 ['Mohsin' 'Engineer' 'M' 29.0 50000.0]
 ['Naveed Fatima' 'Analyst' 'F' 30.0 70000.0]
 ['Babar' 'Engineer' 'F' 25.0 1500000.0]
 ['Aqsa' 'Scientist' 'F' 22.0 nan]
 ['Rafia' 'Analyst' 'F' 29.0 20000.0]
 ['Samra' 'Scientist' 'F' 26.0 115000.0]
 ['Eman' 'Engineer' 'F' 28.0 35000.0]
 ['Abdullah' 'Teacher' 'M' 55.0 nan]
 ['Mosib' 'professor' 'M' 60.0 70000.0]
 ['Ahmed' 'engineer' 'M' nan 90000.0]
 ['Ahsan' 'trainer' 'M' 156.0 110000.0]
 ['Wajid' 'teacher' 'M' 67.0 2000.0]
 ['Naeem' 'trainer' 'M' 80.0 16000.0]
 ['Qaisar' 'professor' 'M' 20.0 170000.0]
 ['Wajid' 'Engineer' 'M' 85.0 190000.0]]


Handle Missing Data:

Replace 'nan' with a specific value, e.g., 0

In [8]:
data_array = np.nan_to_num(data_array, nan=0)

print(data_array)


[['Mukhtar' 'Professor' 'M' 37.0 115000.0]
 ['Azziz' 'Teacher' 'M' 30.0 35000.0]
 ['Mohsin' 'Engineer' 'M' 29.0 50000.0]
 ['Naveed Fatima' 'Analyst' 'F' 30.0 70000.0]
 ['Babar' 'Engineer' 'F' 25.0 1500000.0]
 ['Aqsa' 'Scientist' 'F' 22.0 nan]
 ['Rafia' 'Analyst' 'F' 29.0 20000.0]
 ['Samra' 'Scientist' 'F' 26.0 115000.0]
 ['Eman' 'Engineer' 'F' 28.0 35000.0]
 ['Abdullah' 'Teacher' 'M' 55.0 nan]
 ['Mosib' 'professor' 'M' 60.0 70000.0]
 ['Ahmed' 'engineer' 'M' nan 90000.0]
 ['Ahsan' 'trainer' 'M' 156.0 110000.0]
 ['Wajid' 'teacher' 'M' 67.0 2000.0]
 ['Naeem' 'trainer' 'M' 80.0 16000.0]
 ['Qaisar' 'professor' 'M' 20.0 170000.0]
 ['Wajid' 'Engineer' 'M' 85.0 190000.0]]


Perform Operations:

Assuming the salary is in the 5th column (index 4)

In [9]:
salaries = data_array[:, 4].astype(float)
average_salary = np.mean(salaries)

print(f"Average Salary: {average_salary}")

Average Salary: nan


Filter Data:
 Assuming age is in the 4th column (index 3)

In [10]:
ages = data_array[:, 3].astype(float)
filtered_data = data_array[ages > 30]

print(filtered_data)

[['Mukhtar' 'Professor' 'M' 37.0 115000.0]
 ['Abdullah' 'Teacher' 'M' 55.0 nan]
 ['Mosib' 'professor' 'M' 60.0 70000.0]
 ['Ahsan' 'trainer' 'M' 156.0 110000.0]
 ['Wajid' 'teacher' 'M' 67.0 2000.0]
 ['Naeem' 'trainer' 'M' 80.0 16000.0]
 ['Wajid' 'Engineer' 'M' 85.0 190000.0]]


Sort Data:Sort by salary (5th column, index 4)

In [11]:
sorted_indices = np.argsort(data_array[:, 4].astype(float))
sorted_data = data_array[sorted_indices]

print(sorted_data)

[['Wajid' 'teacher' 'M' 67.0 2000.0]
 ['Naeem' 'trainer' 'M' 80.0 16000.0]
 ['Rafia' 'Analyst' 'F' 29.0 20000.0]
 ['Azziz' 'Teacher' 'M' 30.0 35000.0]
 ['Eman' 'Engineer' 'F' 28.0 35000.0]
 ['Mohsin' 'Engineer' 'M' 29.0 50000.0]
 ['Naveed Fatima' 'Analyst' 'F' 30.0 70000.0]
 ['Mosib' 'professor' 'M' 60.0 70000.0]
 ['Ahmed' 'engineer' 'M' nan 90000.0]
 ['Ahsan' 'trainer' 'M' 156.0 110000.0]
 ['Mukhtar' 'Professor' 'M' 37.0 115000.0]
 ['Samra' 'Scientist' 'F' 26.0 115000.0]
 ['Qaisar' 'professor' 'M' 20.0 170000.0]
 ['Wajid' 'Engineer' 'M' 85.0 190000.0]
 ['Babar' 'Engineer' 'F' 25.0 1500000.0]
 ['Aqsa' 'Scientist' 'F' 22.0 nan]
 ['Abdullah' 'Teacher' 'M' 55.0 nan]]


1D Array

In [12]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [13]:
print(type(arr))

<class 'numpy.ndarray'>


## 2d array
height and width

In [14]:
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


## 3d array
height and width and depth

In [15]:
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## Array creation using build in method
np.zeros()

np.ones()

np.full()

np.arange()

np.linspace()

In [16]:
zarray=np.zeros((2,3))
onesarray=np.ones((3,4))
constant_array=np.full((2,2),4)

range_arr=np.arange(0,10,2)#start, stop, stepsize

linespace_arr=np.linspace(0,1,5)#start, stop, interval
print("zero's array= \n",zarray)
print("one's array= \n",onesarray)
print("constant_array =\n",constant_array)
print("Arrange array =\n",range_arr)
print("linespace_array=\n",linespace_arr)

zero's array= 
 [[0. 0. 0.]
 [0. 0. 0.]]
one's array= 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
constant_array =
 [[4 4]
 [4 4]]
Arrange array =
 [0 2 4 6 8]
linespace_array=
 [0.   0.25 0.5  0.75 1.  ]


## Creating array using random number generation

np.random.rand() from 0 to 1

np.random.randn()  from specific distrivution

np.random.randint() from given range

In [19]:
random_array=np.random.rand(2,3)
print(random_array)
normal_array=np.random.randn(2,3)
print("\n",random_array)
randint_array=np.random.randint(2,9)
print("\n",randint_array)

[[0.36838584 0.63565584 0.88283436]
 [0.0946839  0.69145915 0.76849098]]

 [[0.36838584 0.63565584 0.88283436]
 [0.0946839  0.69145915 0.76849098]]

 5


## numpy array attribute and methods

Reshaping

In [21]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
newarr=arr.reshape(2,5) #important in image filterring
print(newarr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


## Remove dimensions

In [22]:
newarr=newarr.reshape(-1)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10]


## Dimension Checking

In [24]:
a=np.array(43)
b=np.array([1,3,45])
c=np.array([[2,4],[2,7]])

print(a.ndim)
print(b.ndim)
print(c.ndim)

0
1
2


## Using ndim Creating Dimensions

In [25]:
arr=np.array([1,2,3,4,5],ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4 5]]]]]
5


## Array Shape

In [26]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


## Data Type of Array

i-integer
f-float
c-complex float
u-unsigned int
m-timedelta
S-string

In [27]:
arr=np.array(["Apple","Banana","Cherry"])
print(arr.dtype)
arr=np.array([1,2,3,4,5], dtype='S')
print(arr.dtype)
arr=np.array([1,2,3,4,5], dtype='f')
print(arr.dtype)

<U6
|S1
float32


##Copying

In [28]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)

arr=np.array([[1,2,3,4,5,6]])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([[1, 2, 3, 4, 5, 6]]), array([], shape=(0, 6), dtype=int64), array([], shape=(0, 6), dtype=int64)]


##Deleting

In [33]:
arr1=np.arange(10)
print(arr1)
arr1=np.delete(arr1,3)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 4 5 6 7 8 9]
