Name:Quratulain<br>
Github:QuratulainkhanAIML1@outlook.com<br>
Topic:Assignment no 1<br>

Installing libraries

In [1]:
%pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [2]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


import libraries

In [3]:
import pandas as pd
import numpy as np

1.Basic array operations

Create 1D,2D,3D Array

In [4]:
#1D array
a1D=np.array([1,2,3,4,5])
print(a1D)

[1 2 3 4 5]


In [5]:
#2D array
a2D=np.array([[1,2,3],[4,5,6]])
print(a2D)

[[1 2 3]
 [4 5 6]]


In [6]:
#3D array
a3D=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a3D)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Slicing an array

In [7]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[2:8])
print(arr[0:8:2])

[3 4 5 6 7 8]
[1 3 5 7]


Arithmetic operations

In [8]:
#Addition
arr1=np.array([1,2,3])
arr2=np.array([7,8,9])
sum=arr1+arr2
sum

array([ 8, 10, 12])

In [9]:
#subtratcion
arr1=np.array([1,2,3])
arr2=np.array([7,8,9])
sub=arr1-arr2
sub

array([-6, -6, -6])

In [10]:
#multiplication
arr1=np.array([1,2,3])
arr2=np.array([7,8,9])
pro=arr1*arr2
pro

array([ 7, 16, 27])

In [11]:
#division
arr1=np.array([8,8,9])
arr2=np.array([8,2,3])
div=arr1/arr2
div

array([1., 4., 3.])

2.Array Creation and manipulation

Create array using functions

In [12]:
#using arange()
arr=np.arange(10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
#using linespace()
arr=np.linspace(0,1,6)
arr

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [14]:
#using ones()
arr=np.ones((3,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
#using zeros()
arr=np.zeros((2,2))
arr


array([[0., 0.],
       [0., 0.]])

In [16]:
#using eye()
arr=np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
#using random()
arr=np.random.rand(4)
arr

array([0.74815012, 0.04034713, 0.74586662, 0.25870425])

Reshape an Array

In [18]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
newarr=arr.reshape(2,5) 
print(newarr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [19]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Concatenate and split arrays

In [20]:
#concatenate arrays
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
arr

array([1, 2, 3, 4, 5, 6])

In [21]:
#split arrays
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr1=np.split(arr,3)
arr1

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

Staistical operations

In [22]:
#mean
array=np.array([[-2.5,3.1,7],[10,11,12]])
array.mean()

np.float64(6.766666666666667)

In [23]:
#median
array=np.array([[-2.5,3.1,7],[10,11,12]])
medianvalue=np.median(array)
medianvalue

np.float64(8.5)

In [24]:
#variance
array=np.array([[-2.5,3.1,7],[10,11,12]])
array.var()

np.float64(25.855555555555554)

In [25]:
#standard deviation
array=np.array([[-2.5,3.1,7],[10,11,12]])
array.std()


np.float64(5.084835843520964)

In [26]:
#minimum
array=np.array([[-2.5,3.1,7],[10,11,12]])
minimumvalue=array.min()
minimumindex=np.unravel_index(np.argmin(array),array.shape)
print(f"minimum value:{minimumvalue} , index:{minimumindex}")


minimum value:-2.5 , index:(np.int64(0), np.int64(0))


In [27]:
#maximum
array=np.array([[-2.5,3.1,7],[10,11,12]])
maximumvalue=array.max()
maximumindex=np.unravel_index(np.argmax(array),array.shape)
print(f"maximum value:{maximumvalue} , index:{maximumindex}")

maximum value:12.0 , index:(np.int64(1), np.int64(2))


In [28]:
#sum
array=np.array([[-2.5,3.1,7],[10,11,12]])
array.sum()

np.float64(40.6)

In [29]:
#product
array=np.array([[-2.5,3.1,7],[10,11,12]])
array.prod()

np.float64(-71610.0)

Broadcasting

In [30]:
#Scalar and Array
a=np.array([1,2,3])
b=5
sum=a+b
print(sum)

[6 7 8]


In [31]:
#1D and 2D array
a=np.array([[1],[2],[3]])
b=np.array([10,20,30])
sum=a+b
sum

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

In [32]:
#with compatible shapes
a=np.array([[1,2,3],[4,5,6]])
b=np.array([10,20,30])
sum=a+b
sum

array([[11, 22, 33],
       [14, 25, 36]])

Transpose

In [42]:
# Vectors
v = np.array([1, 2, 3])


# Matrices
A = np.array([[1, 2], [3, 4]])
#transpose
A.T

array([[1, 3],
       [2, 4]])

Perform matrix multiplication.

In [37]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = np.dot(A, B)
result

array([[19, 22],
       [43, 50]])

Determinant

In [39]:

# Determinant
det = np.linalg.det(A)
det

np.float64(-2.0000000000000004)

Inverse

In [40]:
#inverse
inv = np.linalg.inv(A)
inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [43]:
# Coefficient matrix A
A = np.array([[2, 3],
              [3, 4]])

# Right-hand side vector b
b = np.array([8, 11])

# Solve for x
x = np.linalg.solve(A, b)

print("Solution:", x)



Solution: [1. 2.]


slicing

In [44]:
a = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])
a[0:2, 1:]

array([[20, 30],
       [50, 60]])

indexing

In [45]:
a = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])
a[[0, 2], [1, 2]] 

array([20, 90])

Use boolean indexing to filter an array

In [47]:
arr = np.array([10, 20, 30, 40, 50])
condition = arr > 25
filtered = arr[condition]

print("Boolean mask:", condition)
print("Filtered elements:", filtered)

Boolean mask: [False False  True  True  True]
Filtered elements: [30 40 50]



Use fancy indexing to select specific elements from an array.


In [46]:
arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]
# Use fancy indexing
selected = arr[indices]
selected

array([10, 30, 50])

Perform advanced slicing operations.

In [50]:
arr2d = np.array([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])

# Get the first two rows and last two columns
sliced = arr2d[:2, 1:]

print(sliced)

[[20 30]
 [50 60]]


In [51]:
# Get the last row and the first two columns
result = arr2d[-1, :2]
print(result)  # Output: [70 80]

[70 80]


In [48]:
# Extract all even numbers from a sliced sub-array
sub_arr = arr[2:9]
filtered = sub_arr[sub_arr % 2 == 0]

print(filtered)  # Output: [2 4 6 8]

[30 40 50]


Random Sampling

In [55]:
array= [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# Random sample of size 3 (with replacement)
sample_with_replacement = np.random.choice(array, size=3, replace=True)
print(sample_with_replacement)

[5 2 3]


In [57]:
array= [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# Random sample of size 3 (without replacement)
sample_without_replacement = np.random.choice(array, size=3, replace=False)
print(sample_without_replacement)

[5 4 9]


In [58]:
# Random sample of 5 integers between 1 and 100
random_integers = np.random.randint(1, 101, size=5)
print(random_integers)

[28 46 95 66 48]


In [59]:
normal_samples = np.random.normal(loc=0, scale=1, size=5)
print("Normal distribution (mean=0, std=1):", normal_samples)

# Generate 5 random numbers from a normal distribution with mean=5 and std=2
normal_samples2 = np.random.normal(loc=5, scale=2, size=5)
print("Normal distribution (mean=5, std=2):", normal_samples2)

Normal distribution (mean=0, std=1): [-0.19331827  0.55761657  0.66771062  1.35463452 -0.01427011]
Normal distribution (mean=5, std=2): [4.71792935 8.68590382 5.07916842 5.93924629 7.39273996]


Create random samples from a dataset.

In [60]:
# Example dataset (1D array)
dataset = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

# Random sample of 3 elements from the dataset without replacement
sample_without_replacement = np.random.choice(dataset, size=3, replace=False)
print("Random sample without replacement:", sample_without_replacement)

# Random sample of 3 elements from the dataset with replacement
sample_with_replacement = np.random.choice(dataset, size=3, replace=True)
print("Random sample with replacement:", sample_with_replacement)

Random sample without replacement: [70 40 20]
Random sample with replacement: [80 20 60]


In [61]:
# Example 2D dataset (2D array)
dataset_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90], [100, 110, 120]])

# Randomly sample 2 rows without replacement
sampled_rows = dataset_2d[np.random.choice(dataset_2d.shape[0], size=2, replace=False)]
print("Randomly sampled rows:\n", sampled_rows)

# Randomly sample 2 columns (columns are axis 1)
sampled_columns = dataset_2d[:, np.random.choice(dataset_2d.shape[1], size=2, replace=False)]
print("Randomly sampled columns:\n", sampled_columns)

Randomly sampled rows:
 [[10 20 30]
 [40 50 60]]
Randomly sampled columns:
 [[ 30  10]
 [ 60  40]
 [ 90  70]
 [120 100]]


Perform random shuffling of an array.

In [62]:

# Example 1D array
array_1d = np.array([10, 20, 30, 40, 50])

# Shuffle the array in place
np.random.shuffle(array_1d)

print("Shuffled 1D array:", array_1d)

Shuffled 1D array: [40 50 10 30 20]


In [63]:
# Example 2D array (rows)
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Shuffle the rows in place
np.random.shuffle(array_2d)

print("Shuffled 2D array (rows shuffled):\n", array_2d)

Shuffled 2D array (rows shuffled):
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
